Controllers/BreedsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DogKennel_Project.Data;
using DogKennel_Project.Models;

namespace DogKennel_Project.Controllers
{
    public class BreedsController : Controller
    {
        private readonly DogKennel_ProjectContext _context;

        public BreedsController(DogKennel_ProjectContext context)
        {
            _context = context;
        }

        // GET: Breeds
        public async Task<IActionResult> Index()
        {
            var dogKennel_ProjectContext = _context.Breed.Include(b => b.ActivityLevel).Include(b => b.DogGroup).Include(b => b.Size);
            return View(await dogKennel_ProjectContext.ToListAsync());
        }

        // GET: Breeds/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var breed = await _context.Breed
                .Include(b => b.ActivityLevel)
                .Include(b => b.DogGroup)
                .Include(b => b.Size)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (breed == null)
            {
                return NotFound();
            }

            return View(breed);
        }

        // GET: Breeds/Create
        public IActionResult Create()
        {
            ViewData["ActivityLevelId"] = new SelectList(_context.ActivityLevel, "Id", "Activity_Level");
            ViewData["DogGroupId"] = new SelectList(_context.DogGroup, "Id", "Group_Name");
            ViewData["SizeId"] = new SelectList(_context.Size, "Id", "Size_Name");
            return View();
        }

        // POST: Breeds/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Breed_Name,Age_Years,DogGroupId,ActivityLevelId,SizeId")] Breed breed)
        {
            if (ModelState.IsValid)
            {
                _context.Add(breed);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ActivityLevelId"] = new SelectList(_context.ActivityLevel, "Id", "Activity_Level", breed.ActivityLevelId);
            ViewData["DogGroupId"] = new SelectList(_context.DogGroup, "Id", "Group_Name", breed.DogGroupId);
            ViewData["SizeId"] = new SelectList(_context.Size, "Id", "Size_Name", breed.SizeId);
            return View(breed);
        }

        // GET: Breeds/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var breed = await _context.Breed.FindAsync(id);
            if (breed == null)
            {
                return NotFound();
            }
            ViewData["ActivityLevelId"] = new SelectList(_context.ActivityLevel, "Id", "Activity_Level", breed.ActivityLevelId);
            ViewData["DogGroupId"] = new SelectList(_context.DogGroup, "Id", "Group_Name", breed.DogGroupId);
            ViewData["SizeId"] = new SelectList(_context.Size, "Id", "Size_Name", breed.SizeId);
            return View(breed);
        }

        // POST: Breeds/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Breed_Name,Age_Years,DogGroupId,ActivityLevelId,SizeId")] Breed breed)
        {
            if (id != breed.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(breed);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BreedExists(breed.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ActivityLevelId"] = new SelectList(_context.ActivityLevel, "Id", "Activity_Level", breed.ActivityLevelId);
            ViewData["DogGroupId"] = new SelectList(_context.DogGroup, "Id", "Group_Name", breed.DogGroupId);
            ViewData["SizeId"] = new SelectList(_context.Size, "Id", "Size_Name", breed.SizeId);
            return View(breed);
        }

        // GET: Breeds/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var breed = await _context.Breed
                .Include(b => b.ActivityLevel)
                .Include(b => b.DogGroup)
                .Include(b => b.Size)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (breed == null)
            {
                return NotFound();
            }

            return View(breed);
        }

        // POST: Breeds/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var breed = await _context.Breed.FindAsync(id);
            _context.Breed.Remove(breed);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BreedExists(int id)
        {
            return _context.Breed.Any(e => e.Id == id);
        }
    }
}

Controllers/DogGroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DogKennel_Project.Data;
using DogKennel_Project.Models;

namespace DogKennel_Project.Controllers
{
    public class DogGroupsController : Controller
    {
        private readonly DogKennel_ProjectContext _context;

        public DogGroupsController(DogKennel_ProjectContext context)
        {
            _context = context;
        }

        // GET: DogGroups
        public async Task<IActionResult> Index()
        {
            return View(await _context.DogGroup.ToListAsync());
        }

        // GET: DogGroups/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dogGroup = await _context.DogGroup
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dogGroup == null)
            {
                return NotFound();
            }

            return View(dogGroup);
        }

        // GET: DogGroups/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DogGroups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Group_Name,Coat_Type")] DogGroup dogGroup)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dogGroup);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dogGroup);
        }

        // GET: DogGroups/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dogGroup = await _context.DogGroup.FindAsync(id);
            if (dogGroup == null)
            {
                return NotFound();
            }
            return View(dogGroup);
        }

        // POST: DogGroups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Group_Name,Coat_Type")] DogGroup dogGroup)
        {
            if (id != dogGroup.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dogGroup);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DogGroupExists(dogGroup.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dogGroup);
        }

        // GET: DogGroups/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dogGroup = await _context.DogGroup
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dogGroup == null)
            {
                return NotFound();
            }

            return View(dogGroup);
        }

        // POST: DogGroups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dogGroup = await _context.DogGroup.FindAsync(id);
            _context.DogGroup.Remove(dogGroup);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DogGroupExists(int id)
        {
            return _context.DogGroup.Any(e => e.Id == id);
        }
    }
}

Controllers/SizesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DogKennel_Project.Data;
using DogKennel_Project.Models;

namespace DogKennel_Project.Controllers
{
    public class SizesController : Controller
    {
        private readonly DogKennel_ProjectContext _context;

        public SizesController(DogKennel_ProjectContext context)
        {
            _context = context;
        }

        // GET: Sizes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Size.ToListAsync());
        }

        // GET: Sizes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var size = await _context.Size
                .FirstOrDefaultAsync(m => m.Id == id);
            if (size == null)
            {
                return NotFound();
            }

            return View(size);
        }

        // GET: Sizes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Sizes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Size_Name,Shedding_Name")] Size size)
        {
            if (ModelState.IsValid)
            {
                _context.Add(size);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(size);
        }

        // GET: Sizes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var size = await _context.Size.FindAsync(id);
            if (size == null)
            {
                return NotFound();
            }
            return View(size);
        }

        // POST: Sizes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Size_Name,Shedding_Name")] Size size)
        {
            if (id != size.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(size);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SizeExists(size.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(size);
        }

        // GET: Sizes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var size = await _context.Size
                .FirstOrDefaultAsync(m => m.Id == id);
            if (size == null)
            {
                return NotFound();
            }

            return View(size);
        }

        // POST: Sizes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var size = await _context.Size.FindAsync(id);
            _context.Size.Remove(size);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SizeExists(int id)
        {
            return _context.Size.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dog_Kennel_Project</title>

    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
    <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: FlexStart - v1.1.0
    * Template URL: https://bootstrapmade.com/flexstart-bootstrap-startup-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>
<body>
    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top">
        <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

            <a href="@Url.Action("Index", "Home")" class="logo d-flex align-items-center">
                <img src="~/assets/img/logo.png" alt="">
                <span>Dog Kennel Club</span>
            </a>

            <nav id="navbar" class="navbar">
                <ul>
                    <li><a class="nav-link scrollto active" href="@Url.Action("Index", "Home")">Home</a></li>
                    <li><a class="nav-link scrollto" href="@Url.Action("Index", "ActivityLevels")">Activity Level</a></li>
                    <li><a class="nav-link scrollto" href="@Url.Action("Index", "DogGroups")">Group</a></li>
                    <li><a class="nav-link scrollto" href="@Url.Action("Index", "Sizes")">Size</a></li>
                    <li><a class="nav-link scrollto" href="@Url.Action("Index", "Breeds")">Breed</a></li>
                </ul>
                <partial name="_LoginPartial" />
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->

        </div>
    </header><!-- End Header -->
    <!-- ======= Hero Section ======= -->
    <section id="hero" class="hero d-flex align-items-center">

        <div class="container">
            <div class="row">
                <div class="col-lg-6 d-flex flex-column justify-content-center">
                    <h1 data-aos="fade-up">For the Love of All Things Dog.</h1>
                    <h2 data-aos="fade-up" data-aos-delay="400">
                        If you’ve got dog questions,
                        we've got dog answers. Find The Right Breed
                    </h2>
                    <div data-aos="fade-up" data-aos-delay="600">
                        <div class="text-center text-lg-start">
                            <a href="@Url.Action("Index", "Home")" class="btn-get-started scrollto d-inline-flex align-items-center justify-content-center align-self-center">
                                <span>Get Started</span>
                                <i class="bi bi-arrow-right"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 hero-img" data-aos="zoom-out" data-aos-delay="200">
                    <img src="~/assets/img/hero-img.png" class="img-fluid" alt="">
                </div>
            </div>
        </div>

    </section><!-- End Hero -->

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <!-- ======= Values Section ======= -->
    <section id="values" class="values">

        <div class="container" data-aos="fade-up">

            <header class="section-header">
                <h2>Our Goal</h2>
                <p>Everything you need to know about getting a dog</p>
            </header>

            <div class="row">

                <div class="col-lg-4">
                    <div class="box" data-aos="fade-up" data-aos-delay="200">
                        <img src="assets/img/values-1.png" class="img-fluid" alt="">
                        <h3>Everything you need to know</h3>
                        <p>Getting your first dog is one of the most exciting things you will ever do! We have made a step-by-step guide to help you on your way.</p>
                    </div>
                </div>

                <div class="col-lg-4 mt-4 mt-lg-0">
                    <div class="box" data-aos="fade-up" data-aos-delay="400">
                        <img src="assets/img/values-2.png" class="img-fluid" alt="">
                        <h3>Find the right breed for you</h3>
                        <p>With 221 pedigree dog breeds, finding one that's perfect for you can be difficult. Explore our Breeds A to Z to discover the ideal breed.</p>
                    </div>
                </div>

                <div class="col-lg-4 mt-4 mt-lg-0">
                    <div class="box" data-aos="fade-up" data-aos-delay="600">
                        <img src="assets/img/values-3.png" class="img-fluid" alt="">
                        <h3>Find a puppy or a rescue dog</h3>
                        <p>Ready to buy a dog? Why not use our Find a Puppy service, whether you're looking for a pedigree puppy or a rescue dog.</p>
                    </div>
                </div>

            </div>

        </div>

    </section><!-- End Values Section -->

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">

        <div class="footer-top">
            <div class="container">
                <div class="row gy-4">
                    <div class="col-lg-5 col-md-12 footer-info">
                        <a href="index.html" class="logo d-flex align-items-center">
                            <img src="~/assets/img/logo.png" alt="">
                            <span>Dog Kennel Club</span>
                        </a>
                        <p>Everything you need to know about getting a dog.</p>
                        <div class="social-links mt-3">
                            <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                            <a href="#" class="instagram"><i class="bi bi-instagram bx bxl-instagram"></i></a>
                            <a href="#" class="linkedin"><i class="bi bi-linkedin bx bxl-linkedin"></i></a>
                        </div>
                    </div>

                    <div class="col-lg-2 col-6 footer-links">
                        <h4>Useful Links</h4>
                        <ul>
                            <li><i class="bi bi-chevron-right"></i> <a href="@Url.Action("Index", "Home")">Home</a></li>
                            <li><i class="bi bi-chevron-right"></i> <a href="@Url.Action("Index", "ActivityLevels")">Activity Level</a></li>
                            <li><i class="bi bi-chevron-right"></i> <a href="@Url.Action("Index", "DogGroups")">Group</a></li>
                            <li><i class="bi bi-chevron-right"></i> <a href="@Url.Action("Index", "Sizes")">Size</a></li>
                            <li><i class="bi bi-chevron-right"></i> <a href="@Url.Action("Index", "Breeds")">Breed</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
                        <h4>Contact Us</h4>
                        <p>
                            25 Springs Road <br>
                            East Tamaki, Auckland<br>
                            New Zealand <br><br>
                            <strong>Phone:</strong> +64 3 345 6789<br>
                            <strong>Email:</strong> info@visioncollege.ac.nz<br>
                        </p>

                    </div>

                </div>
            </div>
        </div>

        <div class="container">
            <div class="copyright">
                &copy; Copyright <strong><span>Dog Kennel Club</span></strong>. All Rights Reserved
            </div>
            <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you purchased the pro version. -->
                <!-- Licensing information: https://bootstrapmade.com/license/ -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/flexstart-bootstrap-startup-template/ -->
                Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
            </div>
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.js"></script>
    <script src="~/assets/vendor/aos/aos.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>
    <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/assets/vendor/purecounter/purecounter.js"></script>
    <script src="~/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>

    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>

</body>
</html>